version: "3.9"

services:
  app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
